/* Generated by cbindgen. Do not edit manually. */

#ifndef CALCPI_H
#define CALCPI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes for C API
 */
#define CALCPI_SUCCESS 0

#define CALCPI_INVALID_ARGUMENT -1

#define CALCPI_INTERNAL_ERROR -2

/**
 * Opaque pointer type for C API
 *
 * This wraps MonteCarloPi and hides its internal structure from C code.
 */
typedef struct calcpi_monte_carlo_pi {
  const void *_private;
} calcpi_monte_carlo_pi;

/**
 * Create a new MonteCarloPi instance
 *
 * # Arguments
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Pointer to the newly created calculator, or NULL if creation fails
 *
 * # Safety
 * The caller must ensure `status` is a valid pointer.
 */
struct calcpi_monte_carlo_pi *calcpi_monte_carlo_pi_new(int32_t *status);

/**
 * Calculate Pi using Monte Carlo method
 *
 * # Arguments
 * * `calc` - Calculator instance
 * * `samples` - Number of samples to generate
 * * `result` - Pointer to store the Pi estimate
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Status code (0 on success)
 *
 * # Safety
 * The caller must ensure all pointers are valid.
 */
int32_t calcpi_monte_carlo_pi_calculate(struct calcpi_monte_carlo_pi *calc,
                                        uint64_t samples,
                                        double *result,
                                        int32_t *status);

/**
 * Get the current Pi estimate
 *
 * # Arguments
 * * `calc` - Calculator instance
 * * `result` - Pointer to store the Pi estimate
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Status code (0 on success)
 *
 * # Safety
 * The caller must ensure all pointers are valid.
 */
int32_t calcpi_monte_carlo_pi_estimate(const struct calcpi_monte_carlo_pi *calc,
                                       double *result,
                                       int32_t *status);

/**
 * Get the total number of samples
 *
 * # Arguments
 * * `calc` - Calculator instance
 * * `result` - Pointer to store the total samples count
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Status code (0 on success)
 *
 * # Safety
 * The caller must ensure all pointers are valid.
 */
int32_t calcpi_monte_carlo_pi_total_samples(const struct calcpi_monte_carlo_pi *calc,
                                            uint64_t *result,
                                            int32_t *status);

/**
 * Get the number of points inside the circle
 *
 * # Arguments
 * * `calc` - Calculator instance
 * * `result` - Pointer to store the inside circle count
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Status code (0 on success)
 *
 * # Safety
 * The caller must ensure all pointers are valid.
 */
int32_t calcpi_monte_carlo_pi_inside_circle(const struct calcpi_monte_carlo_pi *calc,
                                            uint64_t *result,
                                            int32_t *status);

/**
 * Reset all statistics
 *
 * # Arguments
 * * `calc` - Calculator instance
 * * `status` - Pointer to store the status code
 *
 * # Returns
 * * Status code (0 on success)
 *
 * # Safety
 * The caller must ensure all pointers are valid.
 */
int32_t calcpi_monte_carlo_pi_reset(struct calcpi_monte_carlo_pi *calc, int32_t *status);

/**
 * Release the calculator instance
 *
 * # Arguments
 * * `calc` - Calculator instance to release
 *
 * # Safety
 * The caller must ensure `calc` is a valid pointer returned from `calcpi_monte_carlo_pi_new`
 * and has not been released already.
 */
void calcpi_monte_carlo_pi_release(struct calcpi_monte_carlo_pi *calc);

#endif  /* CALCPI_H */
